config/routes.rb
Rails.application.routes.draw do

  resources :timeline, only: [:index]

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :password, only: [:show, :update]
    resource :notification, only: [:show, :update]
  end

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "authentications"}
  resources :users, only: [:show] do
    collection do
      get :autocomplete
      post :email_validate
    end

    scope module: 'users' do
      resources :projects, only: [:index]
      resources :invitements, only: :index
      resources :funs, only: :index
      resource :activities, only: :show
    end
  end
  
  resources :delivering_projects, only: [:index, :create]

  resources :stars, only: [:create] do 
    collection do
      delete :destroy
    end
  end

  resources :events, only: [:index]

  resources :funs, only: [:create] do
    collection do
      delete :destroy
    end
  end

  resources :talks, only: [:create] do
    collection do
      get :talk_content
    end
  end

  resources :about do
    collection do
      get :index
      get :partner
      get :service
      get :law
      get :job
      get :venture
      get :guide
    end
  end
  resources :refine
  resources :categories do
    collection do
      get :autocomplete
    end
  end
  resources :cities do
    collection do
      get :autocomplete
    end
  end

  resources :explore do
    collection do
      get :all
      get :categories
      get :trend
      get :search
    end
  end

  resources :syndicates
  resources :investments, only: [:index, :create]

  resources :interest_users, only: [:index]
  resources :jobs, only: [:index] do
    collection do
      get :search
    end
  end

  resources :logos, only: [:create]
  resources :screenshots, only: [:create]
  resources :projects, except: [:index] do
    member do
      post :publish
      post :invite
      get :team
      get :invest
      patch :dirty_update
      patch :screenshots_update
    end
    resources :members do
      collection do
        get :owner
        get :team_story
        post :update_team_story
        get :autocomplete
        post :invite
      end
    end

    resources :person_requires do
      collection do
        get :admin
      end

      member do
        patch :close
        patch :open
        post :interest
      end
    end
  end

  resources :investors do
    collection do
      get :autocomplete
      get :search
      get :basic
      get :idea
      get :prove
      get :info
      post :submit
    end
  end

  resources :investideas, only: [:index, :create]
  resources :cards, only: [:index, :create]
  resources :bank_statements, only: [:index, :create]

  resources :money_requires do
    member do
      post :add_leader
      patch :add_leader
      post :leader_reject
      patch :leader_reject
      post :leader_confirm
      patch :leader_confirm
      post :close
      patch :close
      patch :dirty_update
    end
    collection do
      post :dirty_create
      get :dirty_show
      get :opened
      get :history
      get :admin
    end
  end

  resources :messages, only: [:index] do
    collection do
      get :count
    end
  end

  resources :law_iterms do
    collection do
      post :diy
    end
  end

  namespace :admin do
    resources :users
    resources :projects
    resources :investors, only: :index do
      member do
      post :accept
      post :reject
      end
    end
    resources :leaders, only: :index do
      collection do
      post :accept
      post :reject
      end
    end
    resources :recommends
    resources :invite_codes
    resources :law_iterms
    root :to=> "dashboard#index"
  end
  root :to => "home#index"
  resources :home, only: [] do
    collection do
      get :index
      get :welcome
      get :search
    end
  end
  resources :avatars, only: [:create]
  resources :messages
  resources :conversations, only: [:index ] do
    member do
      post :mark_as_read
    end
    collection do
      get :unread_count
    end
  end

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/conversations_controller.rb
# MessageBox 交谈
class ConversationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    conversation.mark_as_read current_user
  end

  def mark_as_read
    @conversation = Conversation.find( params[:id] )
    if @conversation.mark_as_read current_user
      render_success '已标记为已读'
    else
      render_fail
    end
  end

  def unread_count
    count = current_user.mailbox.conversations(unread: true).distinct.count
    render_success(nil, data: { count: count })
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.slim
.row
  .large-12.columns.container.conversation
    .row
      .large-2.columns
        = link_to user_path(conversation.last_sender) do
          - image_tag(conversation.last_sender.avatar_url, size: '50x50')
      .large-7.columns
        h5 #{conversation.subject}
        p #{raw conversation.last_message.body}
        p.description #{time_ago_in_words(conversation.created_at)}
      .large-3.columns
        - if conversation.is_unread?(current_user)
            button.tiny.hide.mark_as_read data-uri=mark_as_read_conversation_path(conversation) 标记为已读

app/views/conversations/_form.html.slim
= simple_form_for :conversation, url: :conversations, :html=>{'data-abide'=>''} do |f|
  = f.error_notification
  = f.input :recipients, :required => true, :input_html=>{'required'=>''}
  small.error Recipients is null
  = f.input :subject, :required => true, :input_html=>{'required'=>''}
  small.error Subject is null
  = f.input :body, :required => true, :input_html=>{'required'=>''}
  small.error Message content is null

  .form-actions
    = f.button :submit, class: 'btn-primary'
    = submit_tag 'Reset', type: :reset, class: 'button alert'

app/views/conversations/index.html.slim
- content_for(:container) do
  .row
    .large-3.columns.container
      .row
        .large-12.columns
          h4 Inbox
    .large-8.columns.large-offset-1
      - unless @conversations.empty?
        = render partial: 'conversation', collection: @conversations
      - else
        .row
          .large-12.columns.container style='height: 3rem; padding-top: 0.5rem'
            p No Content

app/views/conversations/new.html.slim
h1 Start Conversation
= render 'form'

app/views/conversations/show.html.slim
.row
  .small-10.large-10.columns
    h2 Conversation: #{conversation.subject}
    - first_msg = conversation.receipts_for(current_user).first.message
  .small-2.large-2.columns
    = link_to 'Back', conversations_path, class: 'button', :style=>"float:right;"

ul
  = content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt|
    - message = receipt.message
    - receiver = message.receipts.first.receiver

    - if receiver == current_user
      h5= message.sender.name + "[#{message.sender.email}]" + ": " + message.subject
    - else
      h5= "To: " + receiver.name + "[#{receiver.email}]: " + message.subject

    .panel
      = message.body

  .li
    = render 'messages/form', conversation: conversation