config/routes.rb
Rails.application.routes.draw do

  resources :timeline, only: [:index]

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :password, only: [:show, :update]
    resource :notification, only: [:show, :update]
  end

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "authentications"}
  resources :users, only: [:show] do
    collection do
      get :autocomplete
      post :email_validate
    end

    scope module: 'users' do
      resources :projects, only: [:index]
      resources :invitements, only: :index
      resources :funs, only: :index
      resource :activities, only: :show
    end
  end
  
  resources :delivering_projects, only: [:index, :create]

  resources :stars, only: [:create] do 
    collection do
      delete :destroy
    end
  end

  resources :events, only: [:index]

  resources :funs, only: [:create] do
    collection do
      delete :destroy
    end
  end

  resources :talks, only: [:create] do
    collection do
      get :talk_content
    end
  end

  resources :about do
    collection do
      get :index
      get :partner
      get :service
      get :law
      get :job
      get :venture
      get :guide
    end
  end
  resources :refine
  resources :categories do
    collection do
      get :autocomplete
    end
  end
  resources :cities do
    collection do
      get :autocomplete
    end
  end

  resources :explore do
    collection do
      get :all
      get :categories
      get :trend
      get :search
    end
  end

  resources :syndicates
  resources :investments, only: [:index, :create]

  resources :interest_users, only: [:index]
  resources :jobs, only: [:index] do
    collection do
      get :search
    end
  end

  resources :logos, only: [:create]
  resources :screenshots, only: [:create]
  resources :projects, except: [:index] do
    member do
      post :publish
      post :invite
      get :team
      get :invest
      patch :dirty_update
      patch :screenshots_update
    end
    resources :members do
      collection do
        get :owner
        get :team_story
        post :update_team_story
        get :autocomplete
        post :invite
      end
    end

    resources :person_requires do
      collection do
        get :admin
      end

      member do
        patch :close
        patch :open
        post :interest
      end
    end
  end

  resources :investors do
    collection do
      get :autocomplete
      get :search
      get :basic
      get :idea
      get :prove
      get :info
      post :submit
    end
  end

  resources :investideas, only: [:index, :create]
  resources :cards, only: [:index, :create]
  resources :bank_statements, only: [:index, :create]

  resources :money_requires do
    member do
      post :add_leader
      patch :add_leader
      post :leader_reject
      patch :leader_reject
      post :leader_confirm
      patch :leader_confirm
      post :close
      patch :close
      patch :dirty_update
    end
    collection do
      post :dirty_create
      get :dirty_show
      get :opened
      get :history
      get :admin
    end
  end

  resources :messages, only: [:index] do
    collection do
      get :count
    end
  end

  resources :law_iterms do
    collection do
      post :diy
    end
  end

  namespace :admin do
    resources :users
    resources :projects
    resources :investors, only: :index do
      member do
      post :accept
      post :reject
      end
    end
    resources :leaders, only: :index do
      collection do
      post :accept
      post :reject
      end
    end
    resources :recommends
    resources :invite_codes
    resources :law_iterms
    root :to=> "dashboard#index"
  end
  root :to => "home#index"
  resources :home, only: [] do
    collection do
      get :index
      get :welcome
      get :search
    end
  end
  resources :avatars, only: [:create]
  resources :messages
  resources :conversations, only: [:index ] do
    member do
      post :mark_as_read
    end
    collection do
      get :unread_count
    end
  end

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @recommends = Recommend.all.default_order.includes(:project).limit(3)
    @investors = Investor.default_order.passed.limit(3)
    @person_requires = PersonRequire.all.limit(3)
    render 'nologin'
  end

  def welcome
    @recommends = Recommend.all.default_order.includes(:project).limit(3)
  end

  def search
    @q = params[:q]
    @projects = Project.search do
      fulltext "*#{params[:q]}*"
      paginate page: 1, per_page: 5
    end.results

    @investors = Investor.search do
      fulltext "*#{params[:q]}*"
      paginate page: 1, per_page: 5
      with(:status, 'passed')
    end.results

    @person_requires = PersonRequire.search do
      fulltext "*#{params[:q]}*"
      paginate page: 1, per_page: 5
      with(:status, 'opened')
    end.results
  end

end

app/views/home/login.html.slim
- content_for(:title) do
  | 时间线

.timeline.top-blank ng-controller='TimelineController' ng-init='init(#{@start_with})'
  .row
    .small-12.medium-10.medium-centered.columns
      - if @events.blank?
        #TODO 
        p 时间线为空, 你可以
        ul
          li
            = link_to '浏览并关注项目', explore_index_path
          li
            = link_to '创建项目', new_project_path
          li
            = link_to '关注你喜欢的投资人', investors_path
      - else
        = render partial: 'event', collection: @events
        .event.ng-cloak ng-repeat= 'event in events' ng-bind-html='event'
        .no-content ng-show='no_content_flag' 没有更多内容
        .load-more
          button ng-hide='loading' ng-click='load_more()' 加载更多
          button ng-show='loading' 加载中...

app/views/home/nologin.html.slim
.start-page
  .start-content
    .row
      .small-12.columns
        .row
          .small-12.large-8.columns
            h2.heading  #{ Setting.heading }
            h4.sub-heading #{ Setting.sub_heading }
            = link_to t('start-page.new_project'), new_project_path, class: 'button'
  .start-projects-content
    .row
      .small-12.columns
        h2 #{t('start-page.hot_project')}
        ul.small-block-grid-1.medium-block-grid-2.large-block-grid-3
          - 3.times do |i|
            - recommend = @recommends[i]
            - if recommend.present?
              - project = @recommends[i].project
              li
                .box.project
                  .head
                    .row
                      .small-5.columns
                        = link_to project do
                          - image_tag project.logo.image_url
                      .small-7.columns
                        = link_to project do
                          h5 #{project.name}
                    .subtitle #{project.oneword}
                  .content
                    .tag
                      .row
                        .small-5.columns
                          .type
                            | #{t('start-page.project.owner')}
                        .small-7.columns
                          .item.right
                            = link_to project.owner.name, project.owner
                    .tag
                      .row
                        .small-5.columns
                          .type
                            | #{t('start-page.project.team')}
                        .small-7.columns
                          .item.right.margin-link-wrapper
                            = link_to project.members.size, project_path(project)
                            | #{t('start-page.project.member')}
                    - if (leader = project.try(:opened_money_require).try(:leader)).present?
                      .tag
                        .row
                          .small-5.columns
                            .type
                              | #{t('start-page.project.leader')}
                          .small-7.columns
                            .item.right
                              = link_to leader.name, leader
            - else
              li
                .box.project
                  .head
                    .row
                      .small-5.columns
                        = image_tag 'default-project.jpg'
                      .small-7.columns
                        h5 #{t('start-page.vacancy')}
                    .subtitle  -
                  .content
                    .tag
                      .row
                        .small-5.columns
                          .type
                            | #{t('start-page.project.owner')}
                        .small-7.columns
                          .item.right
                            | #{t('start-page.none')}
                    .tag
                      .row
                        .small-5.columns
                          .type
                            | #{t('start-page.project.team')}
                        .small-7.columns
                          .item.right
                            | #{t('start-page.none')}
                    .tag
                      .row
                        .small-5.columns
                          .type
                            | #{t('start-page.project.leader')}
                        .small-7.columns
                          .item.right
                            | #{t('start-page.none')}
        .text-center
          = link_to t('start-page.all_project'), all_explore_index_path
  hr
  .start-investors-content
    .row
      .small-12.columns
        h2 #{t('start-page.hot_investor')}
        ul.small-block-grid-1.medium-block-grid-2.large-block-grid-3
          - 3.times do |i|
            - investor = @investors[i]
            - if investor.present?
              - user = investor.user
              li
                .box.investor
                  .head
                    .row
                      .small-5.columns
                        = link_to user do
                          - image_tag user.avatar_url
                      .small-7.columns
                        = link_to user do
                          h6 #{user.name}
                        p.subtitle #{user.description}
                  .content
                    .tag
                      | #{t('start-page.investment_case')}
                    .investments
                      - investments = user.investments.default_order.limit(2)
                      - if investments.blank?
                        .investment
                          | #{t('start-page.none')}
                      - else
                        - investments.each do |investment|
                          .investment
                            - if investment.money_require.present?
                              = link_to investment.money_require.project.name, investment.money_require.project
                            - else
                              | #{investment.name}
            - else
              li
                .box.investor
                  .head
                    .row
                      .small-5.columns
                        = image_tag 'default-people.jpg'
                      .small-7.columns
                        h6 #{t('start-page.vacancy')}
                  .content
                    .tag
                      | #{t('start-page.investment_case')}
                    .investments
                      .investment
                        | #{t('start-page.none')}
        .text-center
          = link_to t('start-page.all_investor'), investors_path
  hr
  .start-jobs-content
    .row
      .small-12.columns
        h2 #{t('start-page.startup_job')}
        ul.small-block-grid-1.medium-block-grid-2.large-block-grid-3
          - 3.times do |i|
            - person_require = @person_requires[i]
            - if person_require.present?
              - project = person_require.project
              li
                .box.job
                  .head
                    .row
                      .small-5.columns
                        = link_to project do
                          - image_tag project.logo.image_url
                      .small-7.columns
                        = link_to project do
                          h5 #{project.name}
                    .subtitle #{project.oneword}
                  .content
                    .tag
                      .row
                        .small-4.columns
                          .type
                            | #{t('start-page.job.salary')}
                        .small-8.columns
                          .item.right.ng-cloak
                            | {{ #{person_require.pay} | nfcurrency }}
                    .tag
                      .row
                        .small-4.columns
                          .type
                            | #{t('start-page.job.title')}
                        .small-8.columns
                          .item.right
                            | #{person_require.title}
                    .tag
                      .row
                        .small-4.columns
                          .type
                            | #{t('start-page.job.option')}
                        .small-8.columns
                          .item.right
                            | #{person_require.option} %
            - else
              li
                .box.job
                  .head
                    .row
                      .small-5.columns
                        = image_tag 'default-project.jpg'
                      .small-7.columns
                        h5 #{t('start-page.vacancy')}
                    .subtitle -
                  .content
                    .tag
                      .row
                        .small-4.columns
                          .type
                            | #{t('start-page.job.salary')}
                        .small-8.columns
                          .item.right.ng-cloak
                            | -
                    .tag
                      .row
                        .small-4.columns
                          .type
                            | #{t('start-page.job.title')}
                        .small-8.columns
                          .item
                            | -
                    .tag
                      .row
                        .small-4.columns
                          .type
                            | #{t('start-page.job.option')}
                        .small-8.columns
                          .item
                            | -
        p.text-center
          = link_to t('start-page.all_job'), jobs_path

app/views/home/search.html.slim
- content_for(:title) do
  | #{@q} - 搜索
.search-page.top-blank
  .row
    .small-12.medium-10.medium-centered.columns
      p 
        | 搜索
        em #{@q}
        | 的结果如下:
      ul
        li
          p 项目:
          - if @projects.blank?
            p.no-content 没有搜索结果
          - else
            .row
              .small-12.columns.projects
                = render partial: 'common/project_list_item', collection: @projects, as: :project
                = link_to '搜索更多项目...', search_explore_index_path(q: params[:q]), class: 'more' 
        li
          p 投资人:
          - if @investors.blank?
            p.no-content 没有搜索结果
          - else
            .row
              .small-12.columns.investors
                = render partial: 'investors/investor', collection: @investors
                = link_to '搜索更多投资人...', search_investors_path(q: params[:q]), class: 'more' 
        li
          p 工作:
          - if @person_requires.blank?
            p.no-content 没有搜索结果
          - else
            .row
              .small-12.columns.jobs
                = render partial: "jobs/person_requires", locals: { person_requires: @person_requires }
                = link_to '搜索更多工作...', search_jobs_path(q: params[:q]), class: 'more' 

app/views/home/welcome.html.slim
- content_for(:title) do
  | 欢迎
.welcome.top-blank
  .row
    .small-12.medium-10.medium-centered.columns
      h1 下一步你可以:
      ul.small-block-grid-1.medium-block-grid-2.large-block-grid-3.list
        li
          = link_to '浏览项目', explore_index_path
        li
          = link_to '创建项目', new_project_path
        li
          = link_to '申请认证投资人', basic_investors_path

      .refine-projects-content
        .row
          .small-12.large-10.large-centered.columns
            = render partial: 'refine/refine_project', collection: @recommends, as: :recommend