config/routes.rb
Rails.application.routes.draw do

  resources :timeline, only: [:index]

  namespace :settings do
    resource :profile, only: [:show, :update]
    resource :password, only: [:show, :update]
    resource :notification, only: [:show, :update]
  end

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "authentications"}
  resources :users, only: [:show] do
    collection do
      get :autocomplete
      post :email_validate
    end

    scope module: 'users' do
      resources :projects, only: [:index]
      resources :invitements, only: :index
      resources :funs, only: :index
      resource :activities, only: :show
    end
  end
  
  resources :delivering_projects, only: [:index, :create]

  resources :stars, only: [:create] do 
    collection do
      delete :destroy
    end
  end

  resources :events, only: [:index]

  resources :funs, only: [:create] do
    collection do
      delete :destroy
    end
  end

  resources :talks, only: [:create] do
    collection do
      get :talk_content
    end
  end

  resources :about do
    collection do
      get :index
      get :partner
      get :service
      get :law
      get :job
      get :venture
      get :guide
    end
  end
  resources :refine
  resources :categories do
    collection do
      get :autocomplete
    end
  end
  resources :cities do
    collection do
      get :autocomplete
    end
  end

  resources :explore do
    collection do
      get :all
      get :categories
      get :trend
      get :search
    end
  end

  resources :syndicates
  resources :investments, only: [:index, :create]

  resources :interest_users, only: [:index]
  resources :jobs, only: [:index] do
    collection do
      get :search
    end
  end

  resources :logos, only: [:create]
  resources :screenshots, only: [:create]
  resources :projects, except: [:index] do
    member do
      post :publish
      post :invite
      get :team
      get :invest
      patch :dirty_update
      patch :screenshots_update
    end
    resources :members do
      collection do
        get :owner
        get :team_story
        post :update_team_story
        get :autocomplete
        post :invite
      end
    end

    resources :person_requires do
      collection do
        get :admin
      end

      member do
        patch :close
        patch :open
        post :interest
      end
    end
  end

  resources :investors do
    collection do
      get :autocomplete
      get :search
      get :basic
      get :idea
      get :prove
      get :info
      post :submit
    end
  end

  resources :investideas, only: [:index, :create]
  resources :cards, only: [:index, :create]
  resources :bank_statements, only: [:index, :create]

  resources :money_requires do
    member do
      post :add_leader
      patch :add_leader
      post :leader_reject
      patch :leader_reject
      post :leader_confirm
      patch :leader_confirm
      post :close
      patch :close
      patch :dirty_update
    end
    collection do
      post :dirty_create
      get :dirty_show
      get :opened
      get :history
      get :admin
    end
  end

  resources :messages, only: [:index] do
    collection do
      get :count
    end
  end

  resources :law_iterms do
    collection do
      post :diy
    end
  end

  namespace :admin do
    resources :users
    resources :projects
    resources :investors, only: :index do
      member do
      post :accept
      post :reject
      end
    end
    resources :leaders, only: :index do
      collection do
      post :accept
      post :reject
      end
    end
    resources :recommends
    resources :invite_codes
    resources :law_iterms
    root :to=> "dashboard#index"
  end
  root :to => "home#index"
  resources :home, only: [] do
    collection do
      get :index
      get :welcome
      get :search
    end
  end
  resources :avatars, only: [:create]
  resources :messages
  resources :conversations, only: [:index ] do
    member do
      post :mark_as_read
    end
    collection do
      get :unread_count
    end
  end

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

  def partner
  end

  def service
  end

  def law
  end

  def job
  end

  def venture
  end

  def guide
  end
end

app/views/about/guide.html.slim
- content_for(:title) do
  | 投资指南
.about.row.top-blank
  .small-12.columns
    h4.title 投资指南 

    p 投资于初创项目风险是非常高的，大多初创企业失败，只有极少数赢利。以下指南是有助于您更好地作出投资决策 。

    ol
      li
        p 创业投资是高风险的投资。很可能导致您亏损，因此，您的投入不要超出您生活的承受范围。

      li
        p 计划的改变。创业公司不断改变计划。计划和预测都无法对未来的进行准确的预测。 

      li
        p 从小做起。用你你获得的投资回报做更大的投资。 

      li
        p 多样化。除非你有足够的资金做10个以上的早期投资项目，否则，不要投资。 

      li
        p 跟随顶级投资人进行投资并确保你得到大致相同的投资条件。 

      li
        p 了解你的权利。您可能无法获得与较大投资人同等权利，例如知情权，参与今后几轮或董事会席位的权利。所以，你的回报可能受托于较大的投资者。 

      li 
        p 投资于初创项目是因为你也有首创精神，你们有共同的愿景和价值观，而并非单纯赚钱。

      li 
        p 注意保密。如果初创项目没有公开募集资金技术，请不要透露或发布他们的融资计划。这是初创企业的决定。 

      li 
        p 货比三家。将有成千上万的公司在创业赢发起融资。不要投资于一家公仅仅只是因为它具有良好的媒体反应或不错的投资人。 
      li 
        p 做自己的尽职调查。 创业赢无法给予你全部的商业信息。 

      li 
        p 关于对创业赢的诉讼。创业赢只是单纯的创业信息平台，与任何第三方无关联，您必须同意发生任何损失不追究我们责任。 

      li 
        p 如果有疑问，请不要投资。 

    hr
    p 
      | 这是如何思考创业投资的概述。 
      br
      | 了解更多有关创业投资所面临的风险请参考 
      = link_to '风险提示', venture_about_index_path, target: '_blank'
      | 。

app/views/about/index.html.slim
- content_for(:title) do
  | 关于我们

.about.row.top-blank
  .small-12.columns
    h4.title 关于我们
    p 深圳市创业赢网络科技有限公司，成立于2014年6月，是由一群有简单创业理想，并带着服务于创业企业这一简单想法的创业伙伴，创建的创业众筹网络平台。创业赢期望通过自身努力不断优化网站和制度设计，完善用户体验，创建一个更为透明、开放、合理的创业生态圈。

    h5 我们的团队
    p TODO

    h5 资质信息
    p TODO

app/views/about/job.html.slim
- content_for(:title) do
  | 加入我们
div.row.project.contianer
  div.large-12.columns
    h1 About Job

app/views/about/law.html.slim
- content_for(:title) do
  | 法律法规
div.row.project.contianer
  div.large-12.columns
    h1 About law

app/views/about/partner.html.slim
- content_for(:title) do
  | 合作伙伴
div.row.project.contianer
  div.large-12.columns
    h1 About partner

app/views/about/service.html.slim
- content_for(:title) do
  | 服务条款

.about.row.top-blank
  .small-12.columns

    h4.title 服务条款
    h5 第一条 服务条款的确认与接纳
    ol
      li 以下所述条款和条件即构成您与创业赢平台就使用服务所达成的协议。当您完成注册并在本服务条款前 方囗打√时，即表示您已同意受创业赢平台网站服务协议约束，包括但不限于本协议、创业赢平台会员服务协 议和隐私权政策等。如果您不同意接受全部的条款和条件，请不要在口打√，同时您将无权使用创业赢网络科技的服务。
      li 在合同有效期内，创业赢平台有权随时修改本协议条款和条件，并只需公示于其网站，而无需征得您的 事先同意。修改后的条款应于公示即时生效。在创业赢平台修改服务条款后，您继续使用服务应被视作您已接 受了修改后的条款。
      li 除非得到创业赢平台的书面授权，任何人将不得修改本协议。
      li 创业赢平台提供的网络服务的所有权和最终解释权归创业赢网络有限公司所有。 本协议中，被许可使用创业赢平台服务的用户均简称为“用户”。

    h5 第二条 服务内容
    ol
      li 在用户同意遵守本协议条款前提下，用户有权在创业赢平台网站指定位置上发布符合中国各项法律法规 及规范性文件以及创业赢平台网站服务条款要求的信息。
      li 创业赢平台运用自己的操作系统通过国际互联网络为用户顺利实现在创业赢平台网站的信息发布提供服务。

    h5 第三条 用户权利义务
    ol 
      li 用户有权在创业赢平台网站指定位置上发布符合中国各项法律法规及规范性文件以及创业赢平台网站服务条款要求的信息，并依据本平台服务规则享受创业赢平台提供的各项服务。
      li 用户有义务保证其发布的信息符合法律、法规及创业赢平台网站的相关服务规则，并及时对已发布的信息进行维护和管理。
      li 考虑到创业赢平台产品服务的重要性，用户有义务保证其提供的所有信息（包括但不限于个人注册信息、 发布的项目信息等）真实、准确，无重大遗漏或误导。如因用户提供的信息不准确，不真实，不合法有效，创业赢平台保留结束用户使用创业赢平台各项服务的权利，同时用户应赔偿因此造成的一切损失。
      li 除创业赢平台规定的条件外，用户因其在创业赢平台网站的信息发布行为而达成的交易，应当与交易对 方约定具体交易条件并完成交易。同时，用户明确知道，自己应当对创业赢平台上发布的项目做出独立的投资 判断，创业赢平台不对用户的投资判断承担任何责任。

    h5 第四条 创业赢平台权利义务
    ol
      li 创业赢平台应运用专业电子技术为用户发布信息提供技术服务。
      li 
        | 如用户有如下行为之一的，创业赢平台有权立即停止用户所发布的信息的技术支持，并保存有关记录， 必要时可依据法律法规向国家有关机关报告，并且删除含有该内容的地址、目录或关闭服务器。用户应承担全部法律责任，并赔偿创业赢平台由此受到的损失，包括合理的追索费用：
        ul
          li 用户提供的产品有侵害任何第三方知识产权、财产权等合法权益，或可能对第三方造成不利影响或侵害；
          li 用户利用创业赢平台提供之网络平台进行任何犯罪活动，或宣传散播法律法规禁止散播的信息，或一 切损害创业赢平台利益的活动；
          li 用户有违反本协议任何条款的行为，经创业赢平台警告后仍未更正的；
          li 用户的行为干扰创业赢平台的服务。
      li 用户同意创业赢平台有权依据本协议及本平台服务规则对用户的不合法、不合规行为采取行动，包括但 不限于中断其帐号、删除地址、目录或关闭服务器等。
      li 创业赢平台对本平台发布的信息真实性、及时性和有效性不做任何形式的担保， 对该等信息的理解和理应应当依赖于用户自身判断。

    h5 第五条 免责及责任的限制与排除
    ol
      li 根据本协议，创业赢平台仅为用户提供网络空间及技术服务，对用户发布的信息的真实性、合法性、及时性和有效性不作任何性质的担保及保证，用户理解并使用这些信息应当依赖自身的独立思考和投资判断，除另有说明外，用户不会从创业赢平台收到口头或书面的意见或信息。创业赢平台对用户的投资收益不做任何承诺，同时对投资损失不承担任何责任。
      li 创业赢平台尽力维护网络平台的稳定，但不就电讯系统或互联网的中断或无法运作、技术 故障、计算机错误或病毒、信息损坏或丢失或由此而产生的其他任何性质的破坏而向用户或任何第三方承担赔偿责任。
      li 用户明确同意使用创业赢平台服务的风险由用户个人承担。创业赢平台不担保服务一定能满足用户的要求，用户理解并接受下载或通过创业赢平台产品服务取得的任何信息资料取决于用户自己，并由其承担系统受 损、资料丢失以及其它任何风险。
      li 各方承认本条款反映了各方就协商谈判达成的一致意见。各方均完全了解本条款的后果并进一步承认本 条款的合理性。

    h5 第六条 隐私政策与安全
    ol
      li 
        | 尊重用户个人隐私是创业赢平台的一项基本政策，创业赢平台将尽力维护用户隐私。除非用户授权，创业赢平台一定不会公开、修改或透露用户的注册资料，亦不会公开创业赢平台各项服务中的非公开内容，但以下情况除外：
        ul
          li 为符合国家法律法规强制性规定，或应有权机关要求，提供用户在创业赢平台的网页上发布的信息内 容及其发布时间、互联网地址或者域名。
          li 为维护创业赢平台的知识产权和其他重要权利。
          li 在紧急情况下为维护用户个人和社会大众的隐私安全。
          li 根据本条款相关规定或者创业赢平台认为必要的其他情况下。
      li 用户一旦注册成功成为用户，即得到一个密码和帐号。如果用户未保管好自己的帐号和密码而对用户、 创业赢平台或第三方造成的损害，用户将负全部责任。另外，每个用户应对其帐户中的所有活动和事件负全责。 用户可随时改变您的密码和图标，也可以结束旧的帐户重开一个新帐户。用户同意若发现任何非法使用用户帐 号或安全漏洞的情况，应立即通告创业赢平台。

    h5 第七条 知识产权
    ol
      li 创业赢平台服务涉及到的产品的所有权以及相关软件的知识产权归深圳市创业赢网络科技有限公司所有。
      li 在本平台内，无论是用户原创或是用户得到著作权人授权转载的作品，用户上载的行为即意味着用户或 用户代理的著作权人授权创业赢平台对上载作品享有不可撤销的永久的使用权和收益权，但用户或原著作权人仍保有上载作品的著作权。
      li 用户应当保证其发布的信息不侵犯任何第三方知识产权及其他权利，否则由此给第三方及创业赢平台造成的损失由用户承担。

    h5 第八条 不可抗力
    p 如果由于黑客攻击或政府管制或网络通讯瘫痪等用户对其发生和后果不能预见的事件，双方均确认此属不可抗力；双方应按照不可抗力对影响履行本协议的程度，协商决定是否解除本协议、免除履行本协议的部分义务， 或者延期履行本协议。

    h5 第九条 法律及争议解决
    ol
      li 本协议签署、效力、解释和执行以及争议之解决均应适用中国法律。
      li 因本协议引起之双方争议，应该通过友好协商解决；协商不成的，任一方均可向天津盛邦投资有限公司 所在地人民法院起诉。

    h5 第十条 期限
    p 本协议的期限自用户点击同意之日起算，至用户注销账号之日起自动终止。

    h5 第十一条 协议的转让
    p 除非取得创业赢网络科技的事先书面同意。用户不得将其在本协议项下的权利与义务转让给任何第三方。

    h5 第十二条 其他
    ol
      li 本协议构成用户和创业赢平台间就使用平台的完整的协议，并取代双方就有关本协议所载任何事项于先 前以口头及书面达成的共识。
      li 如本协议的任何条款被视作无效或无法执行，则上述条款可被分离，其余部份则仍具有法律效力。
      li 本协议的标题仅为方便阅读所设，非对条款的定义、限制、解释或描述其范围或界限。
      li 创业赢平台于用户过失或违约时放弃本协议规定的权利的，不得视为其对用户的其他或以后同类之过失或违约行为弃权。

app/views/about/venture.html.slim
- content_for(:title) do
  | 风险提示
.about.row.top-blank
  .small-12.columns
    h4.title 风险提示
    p
      | 每一个投资人必须意识到在创业赢平台上投资一个或多个公司蕴藏着很高的风险，无论这些投资是以直投方式还是与领投人联合投资方式。
    p
      | 在这里并不能保证：
    ul
      li 任何一个投资标的将会盈利
      li 初创项目都能达到预期的商业目标
      li 每一个领投人都拥有丰富的投资经验致使投资人能从投资项目中获得回报。投资于初创项目包含巨大的风险，其中财务风险和运营风险是最显著的。在任何投资中，高收益伴随着高风险，从事早期项目的创业投资，可能使投资者的投资全部亏损，需要注意的是，在做初创期项目投资之前请仔细评估风险。
    p
      | 初创项目所处的是高度竞争的领域，一般能存活下来的企业较少，初创企业一般存在不可预测的问题包括：产品研发、生产、市场营销、财务和运营管理等等。此外，创业可能需要大量的资金，这可能无法通过机构私募，公开市场或其他方式。 

    h5 投资于高科技

    p
      | 投资于高科技初创项目受到来自于技术更新冲击的风险要比传统证券投资要高。初创项目面临的一些具体风险包括：
      ul
        li 快速的技术更新；
        li 产品和技术很可能很快被淘汰；
        li 缺乏专业系统的管理、技术、科研和市场营销方面的培训；
        li 有关专利和知识产权诉讼的可能性; 
        li 政策法规的变化带来的风险

    h5 经济环境影响

    p 任何一项投资的成功，都在一定程度上受托与经济环境的影响。这其中包括信贷市场、股票市场以及资金的流动性。这些都将对初创企业的运营造成不同程度的影响。全球经济的持续性增长，也会受到来自于恐怖袭击和战争等潜在因素的威胁。这些都无法保证初创公司能成功的运作。经济环境的变化可能会不同程度的影响到持有股权的价值。

    h5 未来和过去业绩

    p 任何一个领投人和投资顾问都无法通过初创项目的现有业绩对未来进行准确的预测，这并不能保证所有的投资目标都能达到，甚至会发生亏损。

    h5 初创项目估值的难度

    p 对任何一个初创项目投资标的的估值都是难度巨大的。这其中包括企业运营的不确定性和市场的不确定性。

    p 缺乏对初创项目有效的监督和评估机制

    p 投资人无法全面的获取初创项目的经营信息，这可能使投资人无法及时获取对其投资产生巨大影响的公司信息。这些不确定因素，使投资人无法对其持有的股权进行合理的评估。

    h5 资金持续性

    p 在投资人无论通过直投还是跟投投资初创项目后，初创项目为了持续发展和扩大市场，可能还会在产品研发、服务、管理、法律制度或其他方面需要额外的资金投入，而这些额外资金的供应是无法完全得到保障的。


    p 上述风险并不意味着已经囊括所有投资于初创项目的是所有参与收购的启动股本证风险。每个投资者在决定是否投资于初创项目之前，都应当寻求独立的法律及税务意见并阅读相关投资文件。